In [1]:
from pathlib import Path
from rich import print

### Load configuration

In [2]:
from w2t_bkin import config, ingest, sync, nwb, domain, behavior

In [3]:
cfg = config.load_config("tests/fixtures/configs/valid_config.toml")
print(cfg)

Config(
    project=ProjectConfig(name='w2t-bkin-pipeline'),
    paths=PathsConfig(
        raw_root='tests/fixtures/data/raw',
        intermediate_root='data/interim',
        output_root='data/processed',
        metadata_file='session.toml',
        models_root='models'
    ),
    timebase=TimebaseConfig(
        source='nominal_rate',
        mapping='nearest',
        jitter_budget_s=0.01,
        offset_s=0.0,
        ttl_id=None,
        neuropixels_stream=None
    ),
    acquisition=AcquisitionConfig(concat_strategy='ffconcat'),
    verification=VerificationConfig(mismatch_tolerance_frames=0, warn_on_mismatch=False),
    bpod=BpodConfig(parse=True),
    video=VideoConfig(transcode=TranscodeConfig(enabled=True, codec='h264', crf=20, preset='fast', keyint=15)),
    nwb=NWBConfig(
        link_external_video=True,
        lab='Lab Name',
        institution='Institution Name',
        file_name_template='{session.id}.nwb',
        session_description_template='Session {session.id} on {session.date}'
    ),
    qc=QCConfig(generate_report=True, out_template='qc/{session.id}', include_verification=True),
    logging=LoggingConfig(level='INFO', structured=False),
    labels=LabelsConfig(
        dlc=DLCConfig(run_inference=False, model='model.pb', gputouse=None),
        sleap=SLEAPConfig(run_inference=False, model='sleap.h5')
    ),
    facemap=FacemapConfig(run_inference=False, ROIs=['face', 'left_eye', 'right_eye'])
)

In [4]:
session = config.load_session("tests/fixtures/data/raw/Session-000001/session.toml")
print(session)

Session(
    session=SessionMetadata(
        id='Session-000001',
        subject_id='mouse_001',
        date='2025-01-01',
        experimenter='Borja Esteban',
        description='Test session',
        sex='M',
        age='P60',
        genotype='WT'
    ),
    bpod=BpodSession(
        path='Bpod/*.mat',
        order='name_asc',
        continuous_time=False,
        trial_types=[
            BpodTrialType(
                trial_type=1,
                description='Active wisker touch trials',
                sync_signal='W2T_Audio',
                sync_ttl='ttl_cue'
            ),
            BpodTrialType(
                trial_type=2,
                description='Passive wisker touch trials',
                sync_signal='A2L_Audio',
                sync_ttl='ttl_cue'
            ),
            BpodTrialType(
                trial_type=3,
                description='Microstim trials',
                sync_signal='Microstim',
                sync_ttl='ttl_cue'
            )
        ]
    ),
    TTLs=[
        TTL(id='ttl_hitmiss', description='Hit/Miss signal from behavior', paths='TTLs/*nidq.xa_1_0*.txt'),
        TTL(id='ttl_camera', description='Camera sync pulses', paths='TTLs/*nidq.xa_7_0*.txt'),
        TTL(id='ttl_cue', description='Cue signal from behavior', paths='TTLs/*nidq.xia_3_0*.txt')
    ],
    cameras=[
        Camera(
            id='cam0',
            description='Top-down camera view of mouse',
            paths='Video/top/*.avi',
            order='name_asc',
            ttl_id='ttl_camera'
        ),
        Camera(
            id='cam1',
            description='Left eye pupil camera',
            paths='Video/pupil_left/*.avi',
            order='name_asc',
            ttl_id='ttl_camera'
        )
    ],
    session_dir='/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001'
)

### Ingest and verify

In [5]:
manifest = ingest.discover_files(cfg, session)
manifest = ingest.populate_manifest_counts(manifest)
print(manifest)

Manifest(
    session_id='Session-000001',
    cameras=[
        ManifestCamera(
            camera_id='cam0',
            ttl_id='ttl_camera',
            video_files=[
                '/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001/Video/top/cam0_2025-01-01-00-00-00.avi
'
            ],
            frame_count=8580,
            ttl_pulse_count=8580
        ),
        ManifestCamera(
            camera_id='cam1',
            ttl_id='ttl_camera',
            video_files=[
                '/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001/Video/pupil_left/cam1_2025-01-01-00-00
-00.avi'
            ],
            frame_count=8580,
            ttl_pulse_count=8580
        )
    ],
    ttls=[
        ManifestTTL(
            ttl_id='ttl_hitmiss',
            files=[
                '/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001/TTLs/session.nidq.xa_1_0_hitmiss.txt'
            ]
        ),
        ManifestTTL(
            ttl_id='ttl_camera',
            files=[
                '/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001/TTLs/session.nidq.xa_7_0_frame.txt'
            ]
        ),
        ManifestTTL(
            ttl_id='ttl_cue',
            files=[
                '/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001/TTLs/session.nidq.xia_3_0_cue.txt'
            ]
        )
    ],
    bpod_files=[
        '/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001/Bpod/session_file01.mat',
        '/home/borja/w2t-bkin/tests/fixtures/data/raw/Session-000001/Bpod/session_file02.mat'
    ]
)

In [6]:
verification = ingest.verify_manifest(manifest, tolerance=5, warn_on_mismatch=True)
print(verification)

VerificationResult(
    status='pass',
    camera_results=[
        CameraVerificationResult(
            camera_id='cam0',
            ttl_id='ttl_camera',
            frame_count=8580,
            ttl_pulse_count=8580,
            mismatch=0,
            verifiable=True,
            status='pass'
        ),
        CameraVerificationResult(
            camera_id='cam1',
            ttl_id='ttl_camera',
            frame_count=8580,
            ttl_pulse_count=8580,
            mismatch=0,
            verifiable=True,
            status='pass'
        )
    ]
)

### Parse Bpod behavioral data

In [7]:
from w2t_bkin.events import parse_bpod

bpod_data = parse_bpod(
    session_dir=Path(session.session_dir),  # ..../tests/fixtures/data/raw/Session-000001
    pattern=session.bpod.path,  # 'Bpod/*.mat'
    order="name_asc",
    continuous_time=False,
)

In [8]:
behavior.extract_task(bpod_data)

task abc.Task at 0x136381458714864
Fields:
  action_types: action_types <class 'ndx_structured_behavior.trials_table.ActionTypesTable'>
  event_types: event_types <class 'ndx_structured_behavior.trials_table.EventTypesTable'>
  state_types: state_types <class 'ndx_structured_behavior.trials_table.StateTypesTable'>
  task_arguments: task_arguments <class 'ndx_structured_behavior.task_argument_table.TaskArgumentsTable'>

In [9]:
behavior.extract_task_recording(bpod_data)

/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'event_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()
/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'state_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()
/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'action_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()

task_recording abc.TaskRecording at 0x136383502273120
Fields:
  actions: actions <class 'ndx_structured_behavior.trials_table.ActionsTable'>
  events: events <class 'ndx_structured_behavior.trials_table.EventsTable'>
  states: states <class 'ndx_structured_behavior.trials_table.StatesTable'>

In [10]:
behavior.extract_trials_table(bpod_data)

trials ndx_structured_behavior.trials_table.TrialsTable at 0x136381456117056
Fields:
  colnames: ['start_time' 'stop_time' 'states' 'events' 'actions']
  columns: (
    start_time <class 'hdmf.common.table.VectorData'>,
    stop_time <class 'hdmf.common.table.VectorData'>,
    states_index <class 'hdmf.common.table.VectorIndex'>,
    states <class 'hdmf.common.table.DynamicTableRegion'>,
    events_index <class 'hdmf.common.table.VectorIndex'>,
    events <class 'hdmf.common.table.DynamicTableRegion'>,
    actions_index <class 'hdmf.common.table.VectorIndex'>,
    actions <class 'hdmf.common.table.DynamicTableRegion'>
  )
  description: Trials from Bpod session
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

### Import pose data

### Import facemap data

### Transcode videos for better storage

### Synchronize to reference timebase

In [11]:
ttl_patterns = {ttl.id: ttl.paths for ttl in session.TTLs}
ttl_pulses = sync.get_ttl_pulses(ttl_patterns, session.session_dir)
trial_offsets, warnings = sync.align_bpod_trials_to_ttl(
    trial_type_configs=session.bpod.trial_types,
    bpod_data=bpod_data,
    ttl_pulses=ttl_pulses,
)

TTL channel 'ttl_hitmiss' has 4 unused pulses
TTL channel 'ttl_camera' has 8580 unused pulses

In [12]:
behavior.extract_task(bpod_data)

task abc.Task at 0x136381456113456
Fields:
  action_types: action_types <class 'ndx_structured_behavior.trials_table.ActionTypesTable'>
  event_types: event_types <class 'ndx_structured_behavior.trials_table.EventTypesTable'>
  state_types: state_types <class 'ndx_structured_behavior.trials_table.StateTypesTable'>
  task_arguments: task_arguments <class 'ndx_structured_behavior.task_argument_table.TaskArgumentsTable'>

In [13]:
behavior.extract_task_recording(bpod_data, trial_offsets)

/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'event_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()
/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'state_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()
/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'action_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()

task_recording abc.TaskRecording at 0x136381456115136
Fields:
  actions: actions <class 'ndx_structured_behavior.trials_table.ActionsTable'>
  events: events <class 'ndx_structured_behavior.trials_table.EventsTable'>
  states: states <class 'ndx_structured_behavior.trials_table.StatesTable'>

In [17]:
behavior.extract_trials_table(bpod_data, trial_offsets)

trials ndx_structured_behavior.trials_table.TrialsTable at 0x136381450339616
Fields:
  colnames: ['start_time' 'stop_time' 'states' 'events' 'actions']
  columns: (
    start_time <class 'hdmf.common.table.VectorData'>,
    stop_time <class 'hdmf.common.table.VectorData'>,
    states_index <class 'hdmf.common.table.VectorIndex'>,
    states <class 'hdmf.common.table.DynamicTableRegion'>,
    events_index <class 'hdmf.common.table.VectorIndex'>,
    events <class 'hdmf.common.table.DynamicTableRegion'>,
    actions_index <class 'hdmf.common.table.VectorIndex'>,
    actions <class 'hdmf.common.table.DynamicTableRegion'>
  )
  description: Trials from Bpod session
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

### Assemble NWB

In [18]:
output_dir = Path("data/external/Session-000001")
provenance = {
    "config_hash": "abc123",
    "session_hash": "def456",
    "software": {"name": "w2t_bkin", "version": "0.1.0"},
    "timebase": {"source": "nominal_rate"},
}
nwb_path = nwb.assemble_nwb(manifest, cfg, provenance, output_dir)

/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/pynwb/file.py:492: UserWarning: Date is missing timezone information. Updating to local timezone.
  args_to_set['session_start_time'] = _add_missing_timezone(session_start_time)

### Validate and QC (Phase 5 - not yet implemented)