In [1]:
from pathlib import Path

import pandas as pd

In [2]:
from pynwb import NWBHDF5IO, NWBFile
from rich import print

from w2t_bkin import behavior, bpod, config, pose, session, sync, ttl

### Load configuration

In [3]:
settings = config.load_config("configs/standard.toml")
print(settings)

Config(
    project=ProjectConfig(name='w2t-bkin-pipeline'),
    paths=PathsConfig(
        raw_root=PosixPath('data/raw'),
        intermediate_root=PosixPath('data/interim'),
        output_root=PosixPath('data/processed'),
        metadata_file=PosixPath('session.toml'),
        models_root=PosixPath('models')
    ),
    bpod=BpodConfig(
        parse=True,
        sync=BpodSyncConfig(
            trial_types=[
                BpodSyncTrialType(trial_type=1, sync_signal='W2T_Audio', sync_ttl='ttl_cue'),
                BpodSyncTrialType(trial_type=2, sync_signal='A2L_Audio', sync_ttl='ttl_cue'),
                BpodSyncTrialType(trial_type=3, sync_signal='Microstim', sync_ttl='ttl_cue')
            ]
        )
    ),
    logging=LoggingConfig(level='INFO', structured=False)
)

In [4]:
interim_path = settings.paths.intermediate_root / "Session-000001"
rawdata_dir = settings.paths.raw_root / "Session-000001"

### Ingest and verify

In [5]:
nwbfile = session.create_nwb_file(rawdata_dir / "metadata.toml")
nwbfile

/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/pynwb/file.py:492: UserWarning: Date is missing timezone information. Updating to local timezone.
  args_to_set['session_start_time'] = _add_missing_timezone(session_start_time)
/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/pynwb/file.py:154: UserWarning: Date is missing timezone information. Updating to local timezone.
  args_to_set['date_of_birth'] = _add_missing_timezone(date_of_birth)

root pynwb.file.NWBFile at 0x139087495757248
Fields:
  data_collection: Data collected using Bpod behavioral control system.
Video recorded at 30 fps using synchronized cameras.
Pose estimated using DeepLabCut model trained on lab-specific data.

  devices: {
    bpod <class 'pynwb.device.Device'>,
    camera_0 <class 'pynwb.device.Device'>,
    camera_1 <class 'pynwb.device.Device'>
  }
  experiment_description: Water-to-target behavioral task with simultaneous video tracking.
Animal navigates to target location while pose is tracked using
DeepLabCut and synchronized with Bpod behavioral events.

  experimenter: ['John Doe' 'Jane Smith']
  file_create_date: [datetime.datetime(2025, 11, 27, 17, 44, 34, 539703, tzinfo=tzlocal())]
  identifier: Session-000001
  institution: Neural Dynamics Laboratory, University Example
  keywords: ['behavior' 'pose tracking' 'synchronization' 'water reward' 'navigation']
  lab: Larkum Lab
  notes: Session conducted with standard lighting conditions.
Animal showed normal behavior throughout the session.
All equipment functioning properly.

  pharmacology: None
  protocol: IACUC-2025-001
  related_publications: []
  session_description: Behavioral training session with pose tracking and camera synchronization
  session_id: 000001
  session_start_time: 2025-01-15 14:30:00+01:00
  slices: N/A - in vivo experiment
  source_script: /home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/ipykernel_launcher.py
  source_script_file_name: ipykernel_launcher.py
  stimulus_notes: Visual target displayed on LED screen at variable locations
  subject: subject pynwb.file.Subject at 0x139085304216016
Fields:
  age: P84D
  age__reference: birth
  date_of_birth: 2024-10-23 00:00:00+02:00
  description: Adult male C57BL/6J mouse, 12 weeks old
  genotype: C57BL/6J wild-type
  sex: M
  species: Mus musculus
  strain: C57BL/6J
  subject_id: M001
  weight: 0.025 kg

  surgery: Cranial window implant surgery performed 2 weeks prior to recording.
No complications observed. Animal recovered fully.

  timestamps_reference_time: 2025-01-15 14:30:00+01:00
  virus: None
  was_generated_by: ['w2t_bkin==0.0.4' 'pynwb==3.1.2' 'hdmf==4.1.2' 'deeplabcut==2.3.11'
 'facemap==1.0.8' 'scipy==1.15.3' 'numpy==1.26.4' 'pandas==2.3.3'
 'torch==2.9.1']

### Import events data (TTL signals)

In [6]:
ttl_patterns = {
    "ttl_camera": "TTLs/*.xa_7_0*.txt",
    "ttl_cue": "TTLs/*.xia_3_0*.txt",
}
ttl_pulses = ttl.get_ttl_pulses(rawdata_dir, ttl_patterns)

### Parse Bpod behavioral data

In [7]:
bpod_data = bpod.parse_bpod(rawdata_dir, pattern="Bpod/*.mat", order="name_asc", continuous_time=False)

### Synchronize to reference timebase

In [8]:
trial_offsets, warnings = sync.align_bpod_trials_to_ttl(
    trial_type_configs=settings.bpod.sync.trial_types,
    bpod_data=bpod_data,
    ttl_pulses=ttl_pulses,
)

TTL channel 'ttl_camera' has 8580 unused pulses

### TTLEvents from ttl pulses

In [9]:
ttl_table = ttl.extract_ttl_table(ttl_pulses)
ttl_table

TTLEvents abc.EventsTable at 0x139085303216784
Fields:
  colnames: ['timestamp' 'channel' 'ttl_description' 'source']
  columns: (
    timestamp <class 'abc.TimestampVectorData'>,
    channel <class 'hdmf.common.table.VectorData'>,
    ttl_description <class 'hdmf.common.table.VectorData'>,
    source <class 'hdmf.common.table.VectorData'>
  )
  description: Hardware TTL pulse events from 2 channels, 8583 total pulses
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

### Trials from bpod data

In [10]:
# Extract all behavioral data in one call (simplified API)
task, recording, trials = behavior.extract_behavioral_data(bpod_data, trial_offsets)
task

/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'event_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()
/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'state_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()
/home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'action_type' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()

task abc.Task at 0x139085303215824
Fields:
  action_types: action_types <class 'ndx_structured_behavior.trials_table.ActionTypesTable'>
  event_types: event_types <class 'ndx_structured_behavior.trials_table.EventTypesTable'>
  state_types: state_types <class 'ndx_structured_behavior.trials_table.StateTypesTable'>
  task_arguments: task_arguments <class 'ndx_structured_behavior.task_argument_table.TaskArgumentsTable'>

In [11]:
recording

task_recording abc.TaskRecording at 0x139085303215248
Fields:
  actions: actions <class 'ndx_structured_behavior.trials_table.ActionsTable'>
  events: events <class 'ndx_structured_behavior.trials_table.EventsTable'>
  states: states <class 'ndx_structured_behavior.trials_table.StatesTable'>

In [12]:
trials

trials ndx_structured_behavior.trials_table.TrialsTable at 0x139087495756384
Fields:
  colnames: ['start_time' 'stop_time' 'states' 'events' 'actions']
  columns: (
    start_time <class 'hdmf.common.table.VectorData'>,
    stop_time <class 'hdmf.common.table.VectorData'>,
    states_index <class 'hdmf.common.table.VectorIndex'>,
    states <class 'hdmf.common.table.DynamicTableRegion'>,
    events_index <class 'hdmf.common.table.VectorIndex'>,
    events <class 'hdmf.common.table.DynamicTableRegion'>,
    actions_index <class 'hdmf.common.table.VectorIndex'>,
    actions <class 'hdmf.common.table.DynamicTableRegion'>
  )
  description: Trials from Bpod session
  id: id <class 'hdmf.common.table.ElementIdentifiers'>

### Import pose data

In [13]:
pose_path = interim_path / "dlc-pose/pupil_left" / "cam0_2025-01-01-00-00-00.h5"
pose_data, pose_metadata = dlc_data = pose.import_dlc_pose(pose_path)

In [14]:
skeleton_1 = pose.create_skeleton(
    name="BA_W2T",
    nodes=pose_metadata.bodyparts,  # Use actual bodyparts from the data
)
skeletons = pose.Skeletons(skeletons=[skeleton_1])
skeletons["BA_W2T"]

BA_W2T abc.Skeleton at 0x139085303213808
Fields:
  edges: []
  nodes: ['C1_end' 'C1_end_reverse' 'C1_mid' 'C1_mid_reverse' 'C1_start'
 'C1_start_reverse' 'C2_end' 'C2_end_reverse' 'C2_mid' 'C2_mid_reverse'
 'C2_start' 'C2_start_reverse' 'Opto_light_in' 'Opto_light_out' 'nose'
 'sensor_bottom' 'sensor_top' 'trial_light']

In [15]:
pose_estimation = pose.build_pose_estimation(
    data=dlc_data,  # Use the already loaded tuple (pose_data, pose_metadata)
    reference_times=ttl_table[:][ttl_table[:]["channel"] == "ttl_camera"]["timestamp"].values,
    skeleton=skeletons["BA_W2T"],
)
pose_estimation

PoseEstimation_BA_W2T ndx_pose.pose.PoseEstimation at 0x139085304025664
Fields:
  description: Pose estimation using DeepLabCut. Scorer: DLC_resnet50_BA_W2T_cam0.newOct30shuffle1_150000. Skeleton: BA_W2T
  pose_estimation_series: {
    C1_end <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C1_end_reverse <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C1_mid <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C1_mid_reverse <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C1_start <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C1_start_reverse <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C2_end <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C2_end_reverse <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C2_mid <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C2_mid_reverse <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C2_start <class 'ndx_pose.pose.PoseEstimationSeries'>,
    C2_start_reverse <class 'ndx_pose.pose.PoseEstimationSeries'>,
    Opto_light_in <class 'ndx_pose.pose.PoseEstimationSeries'>,
    Opto_light_out <class 'ndx_pose.pose.PoseEstimationSeries'>,
    nose <class 'ndx_pose.pose.PoseEstimationSeries'>,
    sensor_bottom <class 'ndx_pose.pose.PoseEstimationSeries'>,
    sensor_top <class 'ndx_pose.pose.PoseEstimationSeries'>,
    trial_light <class 'ndx_pose.pose.PoseEstimationSeries'>
  }
  scorer: DLC_resnet50_BA_W2T_cam0.newOct30shuffle1_150000
  skeleton: BA_W2T abc.Skeleton at 0x139085303213808
Fields:
  edges: []
  nodes: ['C1_end' 'C1_end_reverse' 'C1_mid' 'C1_mid_reverse' 'C1_start'
 'C1_start_reverse' 'C2_end' 'C2_end_reverse' 'C2_mid' 'C2_mid_reverse'
 'C2_start' 'C2_start_reverse' 'Opto_light_in' 'Opto_light_out' 'nose'
 'sensor_bottom' 'sensor_top' 'trial_light']

  source_software: DeepLabCut
  source_software_version: unknown

### Import facemap data

### Transcode videos for better storage

### Assemble NWB

In [16]:
# Add TTL events to NWB file
nwbfile.add_acquisition(ttl_table)

# Add trials to NWB file
nwbfile.add_lab_meta_data(task)
nwbfile.add_acquisition(recording)
nwbfile.trials = trials

# Add Pose to NWB file
behavior_pm = nwbfile.create_processing_module(
    name="behavior",
    description="Processed behavioral data including pose estimation",
)
behavior_pm.add(skeletons)
behavior_pm.add(pose_estimation)

nwbfile

root pynwb.file.NWBFile at 0x139087495757248
Fields:
  acquisition: {
    TTLEvents <class 'abc.EventsTable'>,
    task_recording <class 'abc.TaskRecording'>
  }
  data_collection: Data collected using Bpod behavioral control system.
Video recorded at 30 fps using synchronized cameras.
Pose estimated using DeepLabCut model trained on lab-specific data.

  devices: {
    bpod <class 'pynwb.device.Device'>,
    camera_0 <class 'pynwb.device.Device'>,
    camera_1 <class 'pynwb.device.Device'>
  }
  experiment_description: Water-to-target behavioral task with simultaneous video tracking.
Animal navigates to target location while pose is tracked using
DeepLabCut and synchronized with Bpod behavioral events.

  experimenter: ['John Doe' 'Jane Smith']
  file_create_date: [datetime.datetime(2025, 11, 27, 17, 44, 34, 539703, tzinfo=tzlocal())]
  identifier: Session-000001
  institution: Neural Dynamics Laboratory, University Example
  keywords: ['behavior' 'pose tracking' 'synchronization' 'water reward' 'navigation']
  lab: Larkum Lab
  lab_meta_data: {
    task <class 'abc.Task'>
  }
  notes: Session conducted with standard lighting conditions.
Animal showed normal behavior throughout the session.
All equipment functioning properly.

  pharmacology: None
  processing: {
    behavior <class 'pynwb.base.ProcessingModule'>
  }
  protocol: IACUC-2025-001
  related_publications: []
  session_description: Behavioral training session with pose tracking and camera synchronization
  session_id: 000001
  session_start_time: 2025-01-15 14:30:00+01:00
  slices: N/A - in vivo experiment
  source_script: /home/borja/w2t-bkin/.venv/lib/python3.10/site-packages/ipykernel_launcher.py
  source_script_file_name: ipykernel_launcher.py
  stimulus_notes: Visual target displayed on LED screen at variable locations
  subject: subject pynwb.file.Subject at 0x139085304216016
Fields:
  age: P84D
  age__reference: birth
  date_of_birth: 2024-10-23 00:00:00+02:00
  description: Adult male C57BL/6J mouse, 12 weeks old
  genotype: C57BL/6J wild-type
  sex: M
  species: Mus musculus
  strain: C57BL/6J
  subject_id: M001
  weight: 0.025 kg

  surgery: Cranial window implant surgery performed 2 weeks prior to recording.
No complications observed. Animal recovered fully.

  timestamps_reference_time: 2025-01-15 14:30:00+01:00
  trials: trials <class 'ndx_structured_behavior.trials_table.TrialsTable'>
  virus: None
  was_generated_by: ['w2t_bkin==0.0.4' 'pynwb==3.1.2' 'hdmf==4.1.2' 'deeplabcut==2.3.11'
 'facemap==1.0.8' 'scipy==1.15.3' 'numpy==1.26.4' 'pandas==2.3.3'
 'torch==2.9.1']

In [17]:
nwbpath = Path("output/example_1_nwbfile.nwb")
with NWBHDF5IO(nwbpath, mode="w") as io:
    io.write(nwbfile)

### Validate and QC

In [18]:
! nwbinspector output/example_1_nwbfile.nwb

**************************************************
NWBInspector Report Summary

Timestamp: 2025-11-27 17:44:37.019482+01:00
Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
NWBInspector version: 0.6.5

Found 9 issues over 1 files:
       6 - PYNWB_VALIDATION
       3 - BEST_PRACTICE_SUGGESTION
**************************************************


0  PYNWB_VALIDATION
===================

0.0  output/example_1_nwbfile.nwb and 2 other files: root/general/was_generated_by - 'None' object at location 'general/was_generated_by'
       Message: incorrect shape - expected '[*, 2]', got '(9,)'

0.1  output/example_1_nwbfile.nwb: events - 'None' object at location 'acquisition/TTLEvents'
       Message: missing data type VectorData (timestamp)

0.2  output/example_1_nwbfile.nwb: events - 'None' object at location 'acquisition/TTLEvents'
       Message: missing data type DynamicTableRegion (event_type)

0.3  output/example_1_nwbfile.nwb: events - 'None' object at location 'acquisition/TTLEvents'
       Message: missing data type VectorData (value)

1  BEST_PRACTICE_SUGGESTION
===========================

1.4  output/example_1_nwbfile.nwb: check_experimenter_form - 'NWBFile' object at location '/'
       Message: The name of experimenter 'John Doe' does not match any of the accepted DANDI forms: 'LastName, Firstname', 'LastName, FirstName MiddleInitial.' or 'LastName, FirstName, MiddleName'.

1.5  output/example_1_nwbfile.nwb: check_experimenter_form - 'NWBFile' object at location '/'
       Message: The name of experimenter 'Jane Smith' does not match any of the accepted DANDI forms: 'LastName, Firstname', 'LastName, FirstName MiddleInitial.' or 'LastName, FirstName, MiddleName'.

1.6  output/example_1_nwbfile.nwb: check_single_row - 'TaskArgumentsTable' object with name 'task_arguments'
       Message: This table has only a single row; it may be better represented by another data type.

### Load NWB file and inspect contents

In [19]:
with NWBHDF5IO(nwbpath, mode="r") as io:
    read_nwbfile = io.read()